ibm-developer/generator-ibm-service-enablement

- generators/service-cloudant/templates/java-spring/instrumentation/src/main/java/application/cloudant/CloudantClientConfig.java
Update CloudantClientConfig for Spring to add PropertySource annotation.
Signed-off-by: Kate Stanley <katheris@uk.ibm.com>
> bugfix/CloudantClientConfig for Spring

- generators/service-watson-conversation/templates/java-spring/config.json.template
- test/lib/service-helpers.js
Add dependencies for Watson conversation
> Add dependencies for Watson conversation

- generators/service-push/templates/java-spring/config.json.template
- test/lib/service-helpers.js
Add dependencies for Mobilefirst push
> Add dependencies for Mobilefirst push

- generators/service-push/templates/java-spring/config.json.template
- generators/service-watson-conversation/templates/java-spring/config.json.template
- package-lock.json
- package.json
- test/lib/service-helpers.js
> Merge into master

- generators/service-alert-notification/templates/java-liberty/config.json.template
- generators/service-alert-notification/templates/java-spring/config.json.template
- test/lib/service-helpers.js
Add Java service bindings for alert notifications
> Add Java service bindings for alert notifications

- generators/service-alert-notification/templates/node/README.md
- generators/service-alert-notification/templates/node/instrumentation.js
- generators/service-appid/templates/python/requirements.txt
- generators/service-mongodb/index.js
- generators/service-mongodb/templates/localdev-config.json.template
- generators/service-mongodb/templates/mappings.json
- generators/service-mongodb/templates/node/README.md
- generators/service-mongodb/templates/node/instrumentation.js
- generators/service-object-storage/templates/node/README.md
- generators/service-push/index.js
- generators/service-push/templates/localdev-config.json.template
- generators/service-push/templates/mappings.json
- generators/service-push/templates/node/README.md
- generators/service-push/templates/node/dependencies.json
- generators/service-push/templates/node/instrumentation.js
- package-lock.json
- test/app/alertnotification/node/server.js
- test/app/mongodb/node/server.js
- test/app/push/node/server.js
- test/app/server.js
- test/integration-node-express-test.js
- test/integration-python-flask-test.js
* Fixed Push Node implementation
* Added MongoDB implementation Node
* Added Alert-Notification implementation Node
> Joy testing

- generators/lib/Utils.js
- test/app-services-with-deployment-test.js
Was expecting chart folder name to always be set to bluemix.name,
but for Java projects, the chart folder could be given different name.
> Fix services not added to env in deployment.yaml for Java projects.

- generators/language-swift-kitura/index.js
- generators/language-swift-kitura/templates/dependencies.txt
- generators/service-alert-notification/templates/swift/dependencies.txt
- generators/service-appid/templates/swift/dependencies.txt
- generators/service-cloudant/templates/swift/dependencies.txt
- generators/service-mongodb/templates/swift/dependencies.txt
- generators/service-object-storage/templates/swift/dependencies.txt
- generators/service-postgre/templates/swift/dependencies.txt
- generators/service-push/templates/swift/dependencies.txt
- generators/service-redis/templates/swift/dependencies.txt
- generators/service-watson-conversation/templates/swift/dependencies.txt
- test/app-swift-kitura-test.js
Updating generator swiftserver to swift version 4.0
Neil's changes are merge in this PR
> Swift4 update

- generators/app/fallback_bluemix.js
- generators/language-swift-kitura/bluemix-label-mappings.json
- generators/service-alert-notification/index.js
- test/app-node-express-test.js
- test/app-python-flask-test.js
- test/app-swift-kitura-test.js
- test/lib/service-helpers.js
- test/resources/bluemix.json
Cloud Projects should now correctly download code associated with
`alert-notification`.
> Fixed Alert-Notification Scaffolder Name

- generators/service-appid/templates/swift/dependencies.txt
- package-lock.json
- package.json
+ [Reenable AppID support for generator-swiftserver](https://github.ibm.com/arf/planning-swift-solutions/issues/444)
> Publish new AppId version

- generators/language-python-flask/templates/Pipfile.json
- generators/language-python-flask/templates/requirements.txt
For use with `python manage.py livereload` functionality.
> feat: Adding `livereload` package dependency for Python starters

- generators/language-java/templates/java-liberty/config.json.template
- test/app-java-test.js
Update com.ibm.websphere.appserver.api.json to version 1.0.18.
> fix(config): Update java-liberty dependencies version

- .gitignore
- generators/service-mongodb/templates/java-spring/config.json.template
- generators/service-mongodb/templates/java-spring/instrumentation/src/main/java/application/mongodb/MongoClientConfig.java
- test/lib/service-helpers.js
fix: use Mongo CA cert with Spring
> fix: use Mongo CA cert with Spring

- generators/service-alert-notification/templates/swift/dependencies.txt
- generators/service-alert-notification/templates/swift/instrumentation.swift
- generators/service-alert-notification/templates/swift/meta.json
- Co-dependent on CloudEnvironment v6
> feat: update Swift AlertNotifications to v2

- generators/service-alert-notification/templates/swift/dependencies.txt
- generators/service-alert-notification/templates/swift/instrumentation.swift
- generators/service-alert-notification/templates/swift/meta.json
- Co-dependent on CloudEnvironment v6
>  feat: update Swift AlertNotifications to v2

- generators/lib/Utils.js
- test/resources/pipeline-result-node.yml
Allows arguments containing spaces (some services have plans containing spaces)
> fix: quote cf create-service arguments

- generators/language-java/templates/java-liberty/src/main/java/application/ibmcloud/CloudServices.java
- generators/language-java/templates/java-spring/src/main/java/application/ibmcloud/CloudServices.java
- generators/language-swift-kitura/index.js
- test/app-swift-kitura-test.js
- test/resources/mappings.json
In reference to the following issue: https://github.ibm.com/arf/planning-swift-solutions/issues/570
Updated the mappings files to include credentials and conform to the new format.
> fix: resolve and update mappings to include credentials

- generators/lib/Utils.js
Added support for silencing the INFO logs generated from the Utils.js file.
> Added quiet logging support for Utils

- generators/language-swift-kitura/bluemix-label-mappings.json
- generators/language-swift-kitura/index.js
- generators/service-hypersecure-dbaas-mongodb/index.js
- generators/service-hypersecure-dbaas-mongodb/templates/localdev-config.json.template
- generators/service-hypersecure-dbaas-mongodb/templates/mappings.json
- generators/service-hypersecure-dbaas-mongodb/templates/swift/instrumentation.swift
This changes modifies the HyperSecure DBaaS instrumentation for Swift.
> fix: hypersecure instrumentation

- generators/service-hypersecure-dbaas-mongodb/templates/swift/instrumentation.swift
Forgot to commit this file as part of #207.
> fix: adhere to servicename best practices

- generators/language-swift-kitura/index.js
- generators/service-postgre/templates/swift/dependencies.txt
- generators/service-postgre/templates/swift/instrumentation.swift
- generators/service-postgre/templates/swift/meta.json
- package-lock.json
- test/app-swift-kitura-test.js
In order to had the ORM to the Postgre Service, I need to accepted multiple imports and add to check if we need the variable in application.swift
> feat: Add orm to Postgre Service

- generators/service-watson-conversation/templates/python/Pipfile.json
- generators/service-watson-conversation/templates/python/requirements.txt
- generators/service-watson-discovery/templates/python/Pipfile.json
- generators/service-watson-discovery/templates/python/requirements.txt
- generators/service-watson-language-translator/templates/python/Pipfile.json
- generators/service-watson-language-translator/templates/python/requirements.txt
- generators/service-watson-natural-language-classifier/templates/python/Pipfile.json
- generators/service-watson-natural-language-classifier/templates/python/requirements.txt
- generators/service-watson-natural-language-understanding/templates/python/Pipfile.json
- generators/service-watson-natural-language-understanding/templates/python/requirements.txt
- generators/service-watson-personality-insights/templates/python/Pipfile.json
- generators/service-watson-personality-insights/templates/python/requirements.txt
- generators/service-watson-speech-to-text/templates/python/Pipfile.json
- generators/service-watson-speech-to-text/templates/python/requirements.txt
- generators/service-watson-text-to-speech/templates/python/Pipfile.json
- generators/service-watson-text-to-speech/templates/python/requirements.txt
- generators/service-watson-tone-analyzer/templates/python/Pipfile.json
- generators/service-watson-tone-analyzer/templates/python/requirements.txt
- generators/service-watson-visual-recognition/templates/python/Pipfile.json
- generators/service-watson-visual-recognition/templates/python/requirements.txt
Updating Python SDK to support IAM, services affected:
- Watson Assistant and Visual Recognition
> build(iamSupport): update python SDK version to support IAM

- generators/language-swift-kitura/bluemix-label-mappings.json
- generators/lib/generatorbase.js
- generators/resources/scaffolderMapping.json
- generators/service-appid/index.js
- test/app-node-express-test.js
- test/app-python-flask-test.js
- test/app-swift-kitura-test.js
- test/resources/bluemix.json
patch includes removing deprecated auth instead use appid
> fix: create mapping and localdev-config even when sdk is not available

- generators/service-alert-notification/templates/python/instrumentation.py
This was causing build failure in Flask and Django with alert notification
> fix: indentation adjustment in python-alert notification

- generators/service-elephant-sql/templates/swift/dependencies.txt
- generators/service-elephant-sql/templates/swift/instrumentation.swift
- generators/service-postgre/templates/swift/dependencies.txt
- generators/service-postgre/templates/swift/instrumentation.swift
This change upgrades the service instrumentation code for the [Swift Kuery framework](https://developer.ibm.com/swift/2018/12/18/announcing-swiftkuery-3-0/), specifically the [PostgreSQL driver](https://github.com/IBM-Swift/Swift-Kuery-PostgreSQL) and the [ORM library](https://github.com/IBM-Swift/Swift-Kuery-ORM), which leverages the capabilities that comes with [Kitura 2.6](https://developer.ibm.com/swift/2018/12/18/announcing-kitura-2-6/).
> feat: upgrade Swift Kuery service framework

- generators/language-java/templates/java-liberty/src/main/java/application/ibmcloud/CloudServices.java
fix for https://github.ibm.com/arf/planning-languages/issues/789
> fix: Liberty creds fix

- generators/language-java/index.js
- generators/lib/Utils.js
fix: fixing service enablement of knative with updated paths of service.yaml
> fix service yaml for knative

- generators/language-go/index.js
- generators/language-node-express/index.js
- generators/language-python-flask/index.js
- generators/language-swift-kitura/index.js
fix: fixing service enablement of knative with updated paths of service.yaml in other languages too
> knative service yaml other languages

- generators/language-python-flask/index.js
- generators/lib/generatorbase.js
- test/app-python-flask-test.js
- test/app-python-flask-watson-test.js
This is for fixing the Python starters in the CLI, since they are still using the old generators.
> Workaround
